### ISSUE TITLE
아이콘 교체 패치를 적용했으나 (아마도) 적용되지 않음

### ISSUE THREAD

**Issue by laonmofu** [nekoplanet/misskey#6]
### 💡 Summary

윈도우 PWA 다운로드 시 선 적용되어야 하는 아이콘이 적용되지 않는 버그가 있습니다.
https://github.com/laonmofu/nekoplanet/commit/2b52d2fd1ef96d48962603b465f8d899b7b02ab6

### 🥰 Expected Behavior

윈도우 PWA에서 다운로드를 시도하였을 때, 아이콘이 각각 네코플래닛과 네코쟈라시의 것으로 바뀌어서 다운로드 되어야 합니다.

### 🤬 Actual Behavior

네코플래닛 PWA는 아이콘이 적용되지 않았지만
네코쟈라시의 PWA는 아이콘이 적용된 채로 다운로드가 되었습니다.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): 윈도우 10
* Browser: 크롬
* Server URL: nekoplanet.xyz
* Misskey: 2024.3.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* Misskey:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by HotoRas** [comment]
### environment
```md
* Model and OS of the device(s): Windows 10 21H2 (10.0.19044.1566), x64
* Browser: Chrome Beta 126.0.6478.8
* Server URL: nekoplanet.xyz
* Misskey: 2024.3.1+neko-rc
```
### Expected behavior upon the issue
Installed app's icon will draw as Misskey's default.

### Actual behavior
![nekoplanet.xyz를 설치하고 작업 표시줄에 얹어본 이미지.](https://github.com/nekoplanet/misskey/assets/34373595/b42d9b2d-3e91-413a-acaa-38ba2b00c26f) The favicon of the server will appear.

**Comment by laonmofu** [comment]
고양이별과 네코쟈라시 모두에서 작동하는 것 확인했습니다!
(Tested on Windows 10. 맥에서는 이미 잘 작동했었습니다.)
